### ISSUE TITLE
Use torch.quantile() instead of torch.median()

### ISSUE THREAD

**Issue by WHeLiosC** [EdisonLeeeee/MedianGCN#1]
After reading the original paper, I think torch.quantile(h[nbr], q=0.5, dim=0) should be used instead of torch.median(h[nbr], dim=0) in MedianGCN.

**Comment by EdisonLeeeee** [comment]
Yes, you are right, and this was an intentional behavior. We found that both ` torch.quantile`  and ` torch.median`  work similarly with little difference with an even number of elements.
However, ` torch.quantile` is 10x slower than ` torch.median`, so we used ` torch.median` instead.

**Comment by WHeLiosC** [comment]
The training speed becomes particularly slow after changing the function. That is great if it has little effect on the results. Thank you for your reply. Thank you for your reply!
